mysite/mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('socNetwork.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/socNetwork/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = 'soc'
urlpatterns = [
    path('', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('logout/',views.logout, name='logout'),
    path('create-post/', views.create_post, name='create_post'),
    path('my-posts/', views.my_posts, name='my_posts'),
    path('posts/<int:id>/', views.user_posts, name='user_posts'),
    path('like-post/', views.like_post, name='like_post'),
    path('edit-post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete-post/<int:post_id>', views.delete_post, name='delete_post'),
    path('search/', views.search_name, name='search_name'),
    path('main_profile/<str:username>/', views.main_profile, name='main_profile'),
    path('edit_picture/<int:userid>/', views.edit_picture, name='edit_picture'),
    path('follow_user/<int:id>/', views.follow_user, name='follow_user'),
    path('liked_posts/', views.liked_posts, name='liked_posts'),
    path('user/<str:username>/', views.user, name='user'),
    path('user_main_profile/<int:userId>/', views.user_main_profile, name='user_main_profile'),
    path('users_liked_posts/<int:id>/', views.users_liked_posts, name='users_liked_posts'),
    path('profile_info_privacy/<int:id>/', views.profile_info_privacy, name='profile_info_privacy'),
    path('see_posts/<int:postid>/', views.go_to_post, name='go_to_post'),
    path('anonymous_profile/', views.anonymous_profile, name='anonymous_profile'),
    path('accounts/login/', auth_views.LoginView.as_view()),]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/socNetwork/models.py
from email.policy import default
import django
from django.db import models
from django.utils import timezone

# tbilisi_tz = timezone.now()
# print(tbilisi_tz)


class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    profile_pic = models.ImageField(upload_to='static/pfp/', default='static/pfp/default.png')
    profile_info = models.CharField(max_length=20, default='Public')   
    last_login = models.DateTimeField(default=timezone.now)
    
    def check_password(self, password):
        return self.password == password


class Posts(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE)
    poster_type = models.CharField(max_length=20,default='user')
    post_content = models.CharField(max_length=200)
    post_date = models.DateTimeField(auto_now_add=django.utils.timezone.now)
    image = models.ImageField(upload_to='static/img/', blank=True, null=True)
    
class Likes(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE)
    postId = models.ForeignKey(Posts, on_delete=models.CASCADE)
    like_date = models.DateTimeField(auto_now_add=django.utils.timezone.now)

class Followers(models.Model):
    userId = models.IntegerField()
    followerId = models.IntegerField()
    follow_date = models.DateTimeField(auto_now_add=django.utils.timezone.now)

mysite/socNetwork/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.urls import reverse
from django.views import View
from .models import User, Posts, Likes, Followers
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.backends import BaseBackend

# Create your views here.
class MyView(LoginRequiredMixin, View):
    login_url = '/'
    redirect_field_name = 'next'   
   
def user_is_authenticated(request):
    if 'username' in request.session:
        return True
    return False

@csrf_protect
def login(request):
    if not user_is_authenticated(request):
        csrfContext = RequestContext(request)
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('soc:home'))
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = User.objects.filter(username=username, password=password)
            if user:
                request.session['username'] = username
                return HttpResponseRedirect(reverse('soc:home'))
            else:
                print(request.user, 'tu sheeshalaa')
                return render(request, 'registration/login.html', {'error': 'Invalid username or password', 'csrfContext': csrfContext})
        print(request.user)
        request.session['signup'] = True
        return render(request, 'registration/login.html')
    return HttpResponseRedirect(reverse('soc:home'))


def register(request):
    if user_is_authenticated(request):
        return HttpResponseRedirect(reverse('soc:home'))
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = User.objects.filter(username=username)
        if user:
            return render(request, 'register.htm', {'error': 'Username already exists'})
        else:
            user = User(username=username, password=password)
            user.save()
            return HttpResponseRedirect('/')
    if request.method == "GET":
        request.session.pop('signup', None)
        return render(request, 'register.htm')

#@login_required(redirect_field_name='next')
def anonymous_profile(request):
    if user_is_authenticated(request):
        return render(request, 'anonymous.htm')
    return HttpResponseRedirect(reverse('soc:login'))

#@login_required(redirect_field_name='next')
def home(request):
    if user_is_authenticated(request):  
        posts = Posts.objects.all().order_by('-post_date')
        main_posts = []
        users = User.objects.all()

        logined_user_id = User.objects.get(username=request.session['username']).id
        for post in posts:
            user_id_from_likes = Likes.objects.filter(postId=post).values_list('userId', flat=True)
            liked_by_usernames = []
            for user_id in user_id_from_likes:
                liked_by_usernames.append({'username': User.objects.get(id=user_id).username, 'id': user_id,
                                            'profile_pic': User.objects.get(id=user_id).profile_pic})
            for user in users:
                if post.userId.id == user.id and Likes.objects.filter(userId=logined_user_id, postId=post.id):
                    main_posts.append({'post': post, 'user': user, 'liked_by_me': True, 'liked_by': liked_by_usernames})
                if post.userId.id == user.id and not Likes.objects.filter(userId=logined_user_id, postId=post.id):
                    main_posts.append(
                        {'post': post, 'user': user, 'liked_by_me': False, 'liked_by': liked_by_usernames})

        return render(request, 'home.htm', {'posts': main_posts})
    return HttpResponseRedirect(reverse('soc:login'))

#@login_required(redirect_field_name='next')
def edit_post(request, post_id):
    if user_is_authenticated(request):
        post = Posts.objects.get(id=post_id)
        if request.method == "POST":
            post.post_content = request.POST['post_content']
            post.poster_type = request.POST['poster_type']
            image = request.FILES.get('image', False)
            if image:
                post.image = image
                post.save()
            post.save()
            return HttpResponseRedirect(reverse('soc:home'))
        else:
            return render(request, 'edit_post.htm', {'post': post})
    return HttpResponseRedirect(reverse('soc:login'))

#@login_required(redirect_field_name='next')
def create_post(request):
    if user_is_authenticated(request):
        if request.method == 'POST':
            poster_type = request.POST['poster_type']
            post = request.POST['post_content']
            img = request.FILES.get('image', None)
            user = User.objects.get(username=request.session['username'])
            if poster_type == 'anonym':
                post = Posts(userId=user, poster_type=poster_type, post_content=post, image=img)
                post.save()
            elif poster_type == 'user':
                post = Posts(post_content=post, userId=user, image=img)
                post.save()

            return HttpResponseRedirect(reverse('soc:home'))
    return HttpResponseRedirect(reverse('soc:login'))
#@login_required(redirect_field_name='next')
def edit_picture(request, userid):
    if user_is_authenticated(request):
        user = User.objects.get(id=userid)
        username = user.username
        if request.method == "POST":
            image = request.FILES.get('profile_picture', False)
            if image:
                user.profile_pic = image
                user.save()

            return HttpResponseRedirect(reverse('soc:main_profile', args=(username,)))
    return HttpResponseRedirect(reverse('soc:login'))


#@login_required(redirect_field_name='next')
def my_posts(request):
    if user_is_authenticated(request):
        posts = Posts.objects.filter(userId__username=request.session['username']).order_by('-post_date')
        main_posts = []
        for post in posts:
            main_posts.append({'post': post, 'user': {'username': request.session['username'],
                                                    'id': User.objects.get(username=request.session['username']).id,
                                                    'pic': User.objects.get(
                                                        username=request.session['username']).profile_pic}})

        return render(request, 'my_posts.htm', {'posts': main_posts})
    return HttpResponseRedirect(reverse('soc:login'))

#@login_required(redirect_field_name='next')
def main_profile(request, username):
    if user_is_authenticated(request):
        if username != request.session['username']:
            return HttpResponseRedirect(reverse('soc:home'))      
        try:
            user = User.objects.get(username=username)
            
            posts_count = Posts.objects.filter(userId=user).count()
            likes_amount = Likes.objects.filter(userId=user).count()
            liked_amount = Likes.objects.filter(postId__userId=user).count()
            follower_amount = Followers.objects.filter(userId=user.id).count()
            follower_images = []
            for follower in Followers.objects.filter(userId=user.id):
                follower_id = follower.followerId
                follower_images.append({'pic': User.objects.get(id=follower.followerId).profile_pic})
            followed_amount = Followers.objects.filter(followerId=user.id).count()
            followed_images = []
            for followed in Followers.objects.filter(followerId=user.id):
                followed_images.append({'pic': User.objects.get(id=followed.userId).profile_pic})

            post_content_from_liked_posts = Likes.objects.filter(userId=user).values_list('postId__post_content', flat=True)
            user_id_from_follower = Followers.objects.filter(userId=user.id).values_list('followerId', flat=True)
            follower_usernames = []
            for user_id in user_id_from_follower:
                follower_usernames.append({'username': User.objects.get(id=user_id).username, 'id': user_id})
            user_id_from_following = Followers.objects.filter(followerId=user.id).values_list('userId', flat=True)
            following_usernames = []
            for user_id in user_id_from_following:
                following_usernames.append({'username': User.objects.get(id=user_id).username, 'id': user_id})

            followers = zip(follower_usernames, follower_images)
            following = zip(following_usernames, followed_images)
            data = {'user': user, 'posts_count': posts_count, 'likes_amount': likes_amount,
                    'liked_amount': liked_amount, 'follower_amount': follower_amount,
                    'followed_amount': followed_amount, 'followers': followers,
                    'following': following, 'post_content': post_content_from_liked_posts}
            return render(request, 'main_profile.htm', data)
        except:
            return HttpResponseRedirect(reverse('soc:home'))
    return HttpResponseRedirect(reverse('soc:login'))

#@login_required(redirect_field_name='next')
def user_main_profile(request, userId):
    if user_is_authenticated(request):
        user = User.objects.get(id=userId)
        posts_count = Posts.objects.filter(userId=user, poster_type='user').count()
        likes_amount = Likes.objects.filter(userId=user).count()
        liked_amount = Likes.objects.filter(postId__userId=user).count()
        follower_amount = Followers.objects.filter(userId=user.id).count()
        follower_images = []

mysite/socNetwork/templates/anonymous.htm
{% extends 'main.htm' %}

{% block content %}
<div style="text-align:center; margin-top: 150px;">
    <img src="/media/static/img/anonym.webp" alt="Anonymous" width="200" height="200" style="border-radius: 50%;">
    <h1>Anonsymous Can be every registered user from this platform.</h1>
    <h1>You can post anonymously and can be seen by everyone.</h1>

</div>
{% endblock %}

mysite/socNetwork/templates/edit_post.htm
{% extends 'main.htm' %}
{% block content %}
    <div style="text-align: center; margin-top: 200px;" >
        <form action="{% url 'soc:edit_post' post.id %}" method="post" enctype="multipart/form-data">
            <h1 style="text-align: center;">Edit Post</h1>
            {% csrf_token %}  
            <div style="text-align: center;">
                <h3>Audience</h3>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="poster_type" id="flexRadioDefault1" value="anonym">
                    <label class="form-check-label" for="flexRadioDefault1">
                      Anonym Post
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="poster_type" id="flexRadioDefault2" checked value="user">
                    <label class="form-check-label" for="flexRadioDefault2">
                      Public
                    </label>
                  </div>
            </div>
            <div class="input-group" style="width:40%; margin-left:500px;resize: none;">
                <textarea class="form-control" aria-label="With textarea" name="post_content" rows="10" cols="200">{{post.post_content}}</textarea>
            </div>
            <div class="form-group" style="text-align: center; margin-left:40%; margin-right: 50%; width: 300px;">
                <input type="file" name="image" class="form-control" id="formFile">
                <label for="formFile" class="form-label">Upload Item Image</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

mysite/socNetwork/templates/home.htm
{% extends 'main.htm' %}
{% block content %}
<!-- make simple div container as blog post -->
{% if posts %}
{% for p in posts %}

    <div class="blog-post">
        
        <div class="d-flex align-items-end flex-column">
            <div class="dropdown" style="margin-right: 40px;">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </a>
              
                {% if p.user.username == request.session.username %}
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'soc:edit_post' p.post.id %}">Edit Post</a>
                        <a class="dropdown-item" href="{% url 'soc:delete_post' p.post.id %}">Delete Post</a>
                    </div>
                {% else %}
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="#">Report Post</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <div><p>post date : {{ p.post.post_date}}</p></div>
        {% if p.post.poster_type == 'user' and p.user.username != request.session.username %}
            <a href="{% url 'soc:user_main_profile' p.user.id %}">
                <div class="blog-post-title">
                    <img src="{{p.user.profile_pic.url}}" alt="pfp" width="50" height="50" style="border-radius: 50%">
                    <h2 style="font-weight: 700;">{{p.user.username|upper}}</h2>        
                </div>        
            </a>
        {% elif p.post.poster_type == 'user' and p.user.username == request.session.username %}
            <a href="{% url 'soc:main_profile' p.user.username %}">
                <div class="blog-post-title">
                    <img src="{{p.user.profile_pic.url}}" alt="pfp" width="50" height="50" style="border-radius: 50%">
                    <h2 style="font-weight: 700;">{{p.user.username|upper}}</h2>  
                </div>
        </a>
        {% elif p.post.poster_type == 'anonym' and  p.user.username == request.session.username %}
            <a href="{% url 'soc:main_profile' p.user.username %}">
                <div class="blog-post-title">
                <img src="{{p.user.profile_pic.url}}" alt="pfp" width="50" height="50" style="border-radius: 50%;">
                    <h3>{{p.user.username|upper}}</h3>
                </div>
            </a><h4 style="color: rgb(118, 115, 115);margin-top: 7px;">as Anonsymous</h4>
        {% elif p.post.poster_type == 'anonym' and p.user.username != request.session.username %}
            <div class="blog-post-title">
                <img src="/media/static/img/anonym.webp" alt="anonym" width="50" style="border-radius: 50px;">
                <a href="{% url 'soc:anonymous_profile' %}">Anonymous</a>
        
            </div>
        {% endif %}
        
        <div class="blog-post-body">
            <h2 style="width: 100%;"> {{p.post.post_content}}</h2>
        </div>
        {% if p.post.image %}
            <img src="{{p.post.image.url}}" alt="img" width="80%" height="100%">
        {% endif %}
        
            <form action="{% url 'soc:like_post' %}" method="post">
                {% csrf_token %}
                <input type = "hidden" name = "postid" value = {{p.post.id}} />
                {% if p.liked_by|length != 0 %}

                <div class="liked_by">
                    <p style="margin-top:5px;">Liked By : </p>
                    
                    {% if p.liked_by|length < 3 %}
                        <a href="#" data-toggle="modal" data-target="#liked_by{{p.post.id}}">
                            <div style="font-size: 20px;">
                                {% for user in p.liked_by %}
                                    {{ user.username }}
                                {% endfor %}
                            </div>   
                            
                        </a>
                    {% else %}
                            <a href="#" data-toggle="modal" data-target="#liked_by{{p.post.id}}">   
                                <div style="font-size: 20px;">
                                    {{p.liked_by.0.username}},
                                    {{p.liked_by.1.username}}
                                    and {{p.liked_by|length|add:'-2'}} other
                                </div>
                                
                            </a>
    
                    {% endif %}
                    
                </div>
                {% endif %}
                <input type = "hidden" name = "page" value = "home" />
                <div class="form-row align-items-center d-flex justify-content-center">
                {% if p.liked_by_me %}
                    <input type = "hidden" name = "like_status" value = "unlike" />
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-2" style="border-radius: 50px;background-color: rgb(125, 15, 15); 
                        border-color: rgb(233, 83, 83);width: 50px; height: 50px;margin-top:10px;">
                        <div style="position: absolute;
                        top:50%;
                        left:50%;
                        transform: translate(-50%, -50%);margin-top:5px;">
                            <img src="/media/static/icons/dislike.png" alt="dislike" width="51" height="51" style="margin-bottom: 9px;" >
                        </div>
                    </button>
                    </div>
                {% else %}
                <div class="col-auto">
                    <input type = "hidden" name = "like_status" value = "like" />
                    <button type="submit" class="btn btn-primary mb-2" style="border-radius: 50px; width: 50px; height: 50px;margin-top:10px;">
                        <div style="position: absolute;
                        top:50%;
                        left:50%;
                        transform: translate(-50%, -50%);margin-top:5px;">
                            <img src="/media/static/icons/like.png" alt="like" width="75" height="75" style="margin-bottom: 9px;">
                        </div>   
                    </button>                       
                </div>
                {% endif %}   
                    <h5>{{p.liked_by|length}} like </h5>           
                </div>
                
            </form>
    
            <div id="liked_by{{p.post.id}}" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Liked By</h4>
            
                        </div>
                        <div class="modal-body">
                            <ol>
                                {% for usera in p.liked_by %}
                                    <li>
                                        <div style="display: flex;
                                        gap: 10px;
                                        margin-top: 10px;">
                                        <img src="{{usera.profile_pic.url}}" alt="pfp" width="40" height="40" style="border-radius: 50%;">
                                        <h3><a href="{% url 'soc:user_main_profile' usera.id %}">{{usera.username}}</a></h3>
                                        </div>
                                    </li>
                                {% endfor %}
                                
                            </ol>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
            
                </div>
            
            </div>
            
    </div>




{% endfor %}
{% else %}
    <div style="text-align: center;">
        <p>No posts yet</p>
    </div>
{% endif %}
<form action="/logout">
    {% csrf_token %}
    <fieldset style="margin-top: 40px; margin-bottom: 15px;" class="d-flex justify-content-center">
        <button name="submit" type="submit" class="btn btn-danger">Log Out</button>
    </fieldset>

</form>


{% endblock %}

mysite/socNetwork/templates/liked_posts.htm
{% extends 'main.htm' %}
{% block content %}
<!-- make simple div container as blog post -->
{% if posts %}
{% for p in posts %}

    <div class="blog-post">
        <div class="d-flex align-items-end flex-column">
            <div class="dropdown" style="margin-right: 60px;">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </a>
              
                {% if p.user.username == request.session.username %}
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'soc:edit_post' p.post.postId.id %}">Edit Post</a>
                        <a class="dropdown-item" href="{% url 'soc:delete_post' p.post.postId.id %}">Delete Post</a>
                    </div>
                {% else %}
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="#">Report Post</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <div><p>post date : {{ p.post.postId.post_date}}</p></div>
        <!-- make a div container for the title -->
        {% if p.post.postId.poster_type == 'user' and p.user.username != request.session.username %}
            <div class="blog-post-title">
                <img src="{{p.user.profile_pic.url}}" alt="pfp" width="50" style="border-radius: 50px;">
                <a href="{% url 'soc:user_main_profile' p.user.id %}">{{p.user.username|upper}}</a>
        
            </div>
        {% elif p.post.poster_type == 'user' and p.user.username == request.session.username %}
            <div class="blog-post-title">
                <img src="{{p.user.profile_pic.url}}" alt="pfp" width="50" height="50" style="border-radius: 50%">
                <a href="{% url 'soc:main_profile' p.user.username %}">{{p.user.username|upper}}</a>
        
            </div>
        {% elif p.post.postId.poster_type == 'anonym' and  p.user.username == request.session.username %}
            <div class="blog-post-title">
                <img src="{{p.user.profile_pic.url}}" alt="pfp" width="50" style="border-radius: 50px;">
                <a href="{% url 'soc:user_posts' p.user.id %}">{{p.user.username|upper}}</a><h2 style="color: black;margin-top: 7px;">as Anonymous</h2>
        
            </div>
        {% elif p.post.postId.poster_type == 'anonym' and p.user.username != request.session.username %}
            <div class="blog-post-title">
                <img src="/media/static/img/anonym.webp" alt="anonym" width="50" style="border-radius: 50px;">
                <a href="">Anonymous</a>
        
            </div>
        {% endif %}
        <div class="blog-post-body">
            <!-- make a p tag for the body -->
            <h2>{{p.post.postId.post_content}}</h2>
        </div>

        {% if p.post.postId.image %}
            <img src="{{p.post.postId.image.url}}" alt="img" width="500">
        {% endif %}
        
        <!-- make a div container for the body -->
            <form action="{% url 'soc:like_post' %}" method="post">
                {% csrf_token %}
                <input type = "hidden" name = "postid" value = {{p.post.postId.id}} />
                {% if p.liked_by|length != 0 %}
                <div class="liked_by">
                    <p>Liked By : </p>
                    {% for user in p.liked_by %}
                    <h5>{{ user }}</h5>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="form-row align-items-center d-flex justify-content-center">
                <input type = "hidden" name = "page" value = "liked_posts" />
                {% if p.liked_by_me %}
                    <input type = "hidden" name = "like_status" value = "unlike" />
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-2" style="border-radius: 50px;background-color: rgb(233, 83, 83); border-color: rgb(233, 83, 83);">Unlike</button>
                    </div>
                {% else %}
                <div class="col-auto">
                    <input type = "hidden" name = "like_status" value = "like" />
                    <button type="submit" class="btn btn-primary mb-2" style="border-radius: 50px;">Like</button>
                </div>
                {% endif %}
                <h5>{{p.liked_by|length}} like </h5>                 
                </div>
            </form>
        {{p.post.postId.like}}
    
    </div>
    
{% endfor %}
{% else %}
    <div style="text-align: center;">
        <p>No posts yet</p>
    </div>
{% endif %}
<form action="/logout">
    {% csrf_token %}
    <fieldset style="margin-top: 40px; margin-bottom: 15px;" class="d-flex justify-content-center">
        <button name="submit" type="submit" class="btn btn-danger">Log Out</button>
    </fieldset>
</form>
{% endblock %}

mysite/socNetwork/templates/my_posts.htm
{% extends 'main.htm' %}
{% block content %}
<h1 style="text-align: center;">My Profile</h1>
<!-- make simple div container as blog post -->
{% if posts %}
{% for p in posts %}
    
    <div class="blog-post">
        <div class="d-flex align-items-end flex-column">
            <div class="dropdown" style="margin-right: 60px;">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </a>
            
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'soc:edit_post' p.post.id %}">Edit Post</a>
                    <a class="dropdown-item" href="{% url 'soc:delete_post' p.post.id %}">Delete Post</a>
                </div>
            </div>
        </div>
        <div><p>post date : {{ p.post.post_date}}</p></div>
        <!-- make a div container for the title -->
        {% if p.post.poster_type == 'anonym' %}
            <div class="blog-post-title">
                <!-- make a h1 tag for the title -->
                <img src="{{p.user.pic.url}}" alt="pfp" width="50" height="50" style="border-radius: 50%">
                <a href="{% url 'soc:main_profile' p.user.username %}">{{p.user.username|upper}}</a><h2 style="color: black; margin-top: 7px;">as Anonymous</h2>
        
            </div>
        {% else %}
            <div class="blog-post-title">
                <!-- make a h1 tag for the title -->
                <img src="{{p.user.pic.url}}" alt="pfp" width="50" height="50" style="border-radius: 50%">
                <a href="{% url 'soc:main_profile' p.user.username %}">{{p.user.username|upper}}</a>
        
            </div>
        {% endif %}
    
        <div class="blog-post-body">
            <!-- make a p tag for the body -->
            <h2>{{p.post.post_content}}</h2>
        </div>
        {% if p.post.image %}
            <img src="{{p.post.image.url}}" alt="img" width="500">
        {% endif %}
        <!-- make a div container for the body -->
    </div>
    
{% endfor %}
{% else %}
    <div style="text-align: center;">
        <p>No posts yet</p>
    </div>
{% endif %}
<form action="/logout">
    {% csrf_token %}
    <fieldset style="margin-top: 40px; margin-bottom: 15px;" class="d-flex justify-content-center">
        <button name="submit" type="submit" class="btn btn-danger">Log Out</button>
    </fieldset>
</form>
{% endblock %}